version: '3.3'
services:
  hotel-api:
    container_name: nestar-api
    restart: always
    image: node:20.10.0
    ports:
      - 4001:3007
    volumes:
      - ./:/usr/src/nestar
    working_dir: /usr/src/nestar

    networks:
      - monorepo-network

    # FOR_PRODUCTION
    command: bash -c "rm -rf dist && npm install && npm run build && npm run start:prod"

  nestar-batch:
    container_name: nestar-batch
    restart: unless-stopped
    image: node:20.10.0
    ports:
      - 4002:3008
    volumes:
      - ./:/usr/src/nestar
    working_dir: /usr/src/nestar

    networks:
      - monorepo-network

    # FOR_PRODUCTION
    command: bash -c "npm install && npm run build && npm run start:prod:batch"

networks:
  monorepo-network:
    driver: bridge

  # nestar-hotel: localhost: 4006 => container: 3006
  # hotel-api: localhost: 4007 => container: 3007
  # hotel-batch: localhost: 4008 => container: 3008

  # docker compose up -d
  # docker compose start
  # docker compose restart
  # docker compose stop && docker compose rm -f
  # docker compose config
